/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-01 at 16:04:11 UTC 
 * Modify at your own risk.
 */

package com.velan.testandroid4.todoendpoint;

/**
 * Service definition for Todoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TodoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Todoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the todoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://soupraya-test1.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "todoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Todoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Todoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTodo".
   *
   * This request holds the parameters needed by the todoendpoint server.  After setting any optional
   * parameters, call the {@link GetTodo#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetTodo getTodo(java.lang.Long id) throws java.io.IOException {
    GetTodo result = new GetTodo(id);
    initialize(result);
    return result;
  }

  public class GetTodo extends TodoendpointRequest<com.velan.testandroid4.todoendpoint.model.Todo> {

    private static final String REST_PATH = "todo/{id}";

    /**
     * Create a request for the method "getTodo".
     *
     * This request holds the parameters needed by the the todoendpoint server.  After setting any
     * optional parameters, call the {@link GetTodo#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetTodo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTodo(java.lang.Long id) {
      super(Todoendpoint.this, "GET", REST_PATH, null, com.velan.testandroid4.todoendpoint.model.Todo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTodo setAlt(java.lang.String alt) {
      return (GetTodo) super.setAlt(alt);
    }

    @Override
    public GetTodo setFields(java.lang.String fields) {
      return (GetTodo) super.setFields(fields);
    }

    @Override
    public GetTodo setKey(java.lang.String key) {
      return (GetTodo) super.setKey(key);
    }

    @Override
    public GetTodo setOauthToken(java.lang.String oauthToken) {
      return (GetTodo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTodo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTodo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTodo setQuotaUser(java.lang.String quotaUser) {
      return (GetTodo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTodo setUserIp(java.lang.String userIp) {
      return (GetTodo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetTodo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTodo set(String parameterName, Object value) {
      return (GetTodo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTodo".
   *
   * This request holds the parameters needed by the todoendpoint server.  After setting any optional
   * parameters, call the {@link InsertTodo#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.velan.testandroid4.todoendpoint.model.Todo}
   * @return the request
   */
  public InsertTodo insertTodo(com.velan.testandroid4.todoendpoint.model.Todo content) throws java.io.IOException {
    InsertTodo result = new InsertTodo(content);
    initialize(result);
    return result;
  }

  public class InsertTodo extends TodoendpointRequest<com.velan.testandroid4.todoendpoint.model.Todo> {

    private static final String REST_PATH = "todo";

    /**
     * Create a request for the method "insertTodo".
     *
     * This request holds the parameters needed by the the todoendpoint server.  After setting any
     * optional parameters, call the {@link InsertTodo#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertTodo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.velan.testandroid4.todoendpoint.model.Todo}
     * @since 1.13
     */
    protected InsertTodo(com.velan.testandroid4.todoendpoint.model.Todo content) {
      super(Todoendpoint.this, "POST", REST_PATH, content, com.velan.testandroid4.todoendpoint.model.Todo.class);
    }

    @Override
    public InsertTodo setAlt(java.lang.String alt) {
      return (InsertTodo) super.setAlt(alt);
    }

    @Override
    public InsertTodo setFields(java.lang.String fields) {
      return (InsertTodo) super.setFields(fields);
    }

    @Override
    public InsertTodo setKey(java.lang.String key) {
      return (InsertTodo) super.setKey(key);
    }

    @Override
    public InsertTodo setOauthToken(java.lang.String oauthToken) {
      return (InsertTodo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTodo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTodo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTodo setQuotaUser(java.lang.String quotaUser) {
      return (InsertTodo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTodo setUserIp(java.lang.String userIp) {
      return (InsertTodo) super.setUserIp(userIp);
    }

    @Override
    public InsertTodo set(String parameterName, Object value) {
      return (InsertTodo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTodo".
   *
   * This request holds the parameters needed by the todoendpoint server.  After setting any optional
   * parameters, call the {@link ListTodo#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListTodo listTodo() throws java.io.IOException {
    ListTodo result = new ListTodo();
    initialize(result);
    return result;
  }

  public class ListTodo extends TodoendpointRequest<com.velan.testandroid4.todoendpoint.model.CollectionResponseTodo> {

    private static final String REST_PATH = "todo";

    /**
     * Create a request for the method "listTodo".
     *
     * This request holds the parameters needed by the the todoendpoint server.  After setting any
     * optional parameters, call the {@link ListTodo#execute()} method to invoke the remote operation.
     * <p> {@link
     * ListTodo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTodo() {
      super(Todoendpoint.this, "GET", REST_PATH, null, com.velan.testandroid4.todoendpoint.model.CollectionResponseTodo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTodo setAlt(java.lang.String alt) {
      return (ListTodo) super.setAlt(alt);
    }

    @Override
    public ListTodo setFields(java.lang.String fields) {
      return (ListTodo) super.setFields(fields);
    }

    @Override
    public ListTodo setKey(java.lang.String key) {
      return (ListTodo) super.setKey(key);
    }

    @Override
    public ListTodo setOauthToken(java.lang.String oauthToken) {
      return (ListTodo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTodo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTodo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTodo setQuotaUser(java.lang.String quotaUser) {
      return (ListTodo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTodo setUserIp(java.lang.String userIp) {
      return (ListTodo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTodo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTodo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTodo set(String parameterName, Object value) {
      return (ListTodo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTodo".
   *
   * This request holds the parameters needed by the todoendpoint server.  After setting any optional
   * parameters, call the {@link RemoveTodo#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTodo removeTodo(java.lang.Long id) throws java.io.IOException {
    RemoveTodo result = new RemoveTodo(id);
    initialize(result);
    return result;
  }

  public class RemoveTodo extends TodoendpointRequest<Void> {

    private static final String REST_PATH = "todo/{id}";

    /**
     * Create a request for the method "removeTodo".
     *
     * This request holds the parameters needed by the the todoendpoint server.  After setting any
     * optional parameters, call the {@link RemoveTodo#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveTodo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTodo(java.lang.Long id) {
      super(Todoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTodo setAlt(java.lang.String alt) {
      return (RemoveTodo) super.setAlt(alt);
    }

    @Override
    public RemoveTodo setFields(java.lang.String fields) {
      return (RemoveTodo) super.setFields(fields);
    }

    @Override
    public RemoveTodo setKey(java.lang.String key) {
      return (RemoveTodo) super.setKey(key);
    }

    @Override
    public RemoveTodo setOauthToken(java.lang.String oauthToken) {
      return (RemoveTodo) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTodo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTodo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTodo setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTodo) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTodo setUserIp(java.lang.String userIp) {
      return (RemoveTodo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveTodo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTodo set(String parameterName, Object value) {
      return (RemoveTodo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTodo".
   *
   * This request holds the parameters needed by the todoendpoint server.  After setting any optional
   * parameters, call the {@link UpdateTodo#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.velan.testandroid4.todoendpoint.model.Todo}
   * @return the request
   */
  public UpdateTodo updateTodo(com.velan.testandroid4.todoendpoint.model.Todo content) throws java.io.IOException {
    UpdateTodo result = new UpdateTodo(content);
    initialize(result);
    return result;
  }

  public class UpdateTodo extends TodoendpointRequest<com.velan.testandroid4.todoendpoint.model.Todo> {

    private static final String REST_PATH = "todo";

    /**
     * Create a request for the method "updateTodo".
     *
     * This request holds the parameters needed by the the todoendpoint server.  After setting any
     * optional parameters, call the {@link UpdateTodo#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateTodo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.velan.testandroid4.todoendpoint.model.Todo}
     * @since 1.13
     */
    protected UpdateTodo(com.velan.testandroid4.todoendpoint.model.Todo content) {
      super(Todoendpoint.this, "PUT", REST_PATH, content, com.velan.testandroid4.todoendpoint.model.Todo.class);
    }

    @Override
    public UpdateTodo setAlt(java.lang.String alt) {
      return (UpdateTodo) super.setAlt(alt);
    }

    @Override
    public UpdateTodo setFields(java.lang.String fields) {
      return (UpdateTodo) super.setFields(fields);
    }

    @Override
    public UpdateTodo setKey(java.lang.String key) {
      return (UpdateTodo) super.setKey(key);
    }

    @Override
    public UpdateTodo setOauthToken(java.lang.String oauthToken) {
      return (UpdateTodo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTodo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTodo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTodo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTodo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTodo setUserIp(java.lang.String userIp) {
      return (UpdateTodo) super.setUserIp(userIp);
    }

    @Override
    public UpdateTodo set(String parameterName, Object value) {
      return (UpdateTodo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Todoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Todoendpoint}. */
    @Override
    public Todoendpoint build() {
      return new Todoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TodoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTodoendpointRequestInitializer(
        TodoendpointRequestInitializer todoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(todoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
